/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemplos.grafico.arbol.binario.busqueda.avl.diccionario;

import arbol.binario.listaligada.busqueda.avl.ArbolAVL;
import arbol.binario.listaligada.busqueda.avl.NodoAVL;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Ellipse2D;
import java.util.ArrayList;

/**
 *
 * @author 57300
 */
public class Lienzo extends javax.swing.JPanel {

    ArrayList<Ellipse2D> figuras;

    /**
     * Creates new form Lienzo
     */
    public Lienzo() {
        initComponents();
    }

    public void setObjArbol(ArbolAVL objArbol) {
        this.objArbol = objArbol;
        repaint();
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        Graphics2D g2 = (Graphics2D) g;
        figuras = new ArrayList<>();
        if (objArbol != null) {
            objArbol.getRoot().recalcularAncho();
            pintar(g2, getWidth() / 2, 30, objArbol.getRoot());
        }
    }

    private void pintar(Graphics2D g, int x, int y, NodoAVL n) {
        if (n == null) {
        } else {
            int EXTRA = n.getAncho() * (ANCHO);
            Ellipse2D elipse = new Ellipse2D.Double(x, y,
                    DIAMETRO + 50,
                    DIAMETRO);
            figuras.add(elipse);
            g.draw(elipse);

            g.drawString(n.getDato().toString(), x + 12, y + 18);
            if (n.getLi() != null) {
                g.drawLine(x, y, x - ANCHO - EXTRA + RADIO, y + ANCHO + RADIO);
            }
            if (n.getLd() != null) {
                g.drawLine(x, y, x + ANCHO + EXTRA + RADIO, y + ANCHO + RADIO);
            }
            pintar(g, x - ANCHO - EXTRA, y + ANCHO, (NodoAVL) n.getLi());
            pintar(g, x + ANCHO + EXTRA, y + ANCHO, (NodoAVL) n.getLd());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        System.out.println("Me hicieron click en " + evt.getX() + " " + evt.getY());
        System.out.println("figuras " + figuras.size());

        for (Ellipse2D figura : figuras) {
            System.out.println("evaluando " + figura);
            if (figura.contains(evt.getX(), evt.getY())) {
                System.out.println("Me hicieron click en ");
                Graphics2D g2 = (Graphics2D) this.getGraphics();
                g2.setPaint(Color.red);
                g2.fill(figura);
            }
        }
    }//GEN-LAST:event_formMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private ArbolAVL objArbol;
    public static final int DIAMETRO = 30;
    public static final int RADIO = DIAMETRO / 2;
    public static final int ANCHO = 50;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
